### PR TITLE
Get rid of extraneous deps; bump + export Ganache for those in need

### PR DESCRIPTION
**Pull request by jflatow**

### CODE REVIEW

**Review by hayesgm — APPROVED** [review]
So clean.

**Review by coburncoburn — APPROVED** [review]

**Review by coburncoburn — APPROVED** [review]
what does the subprovider actually do?

**Comment by hayesgm** [comment]
Subproviders are basically middleware for Web3 Provider Engine. Basically, each time a request is going to sent to the given provider (e.g. to route to Infura via the HttpProvider in Web3), it actually walks through each sub-provider and like normal middleware, each can read, modify and pass on the given request. For coverage, we use this to note each transaction and pass it on to the next subprovider, so we can at the end run a trace on that transaction. The issue is that a Provider is not a SubProvider, so this is a wrapper for the ganache subprovider mostly because the one from 0x's library is way out of date.

**Comment by hayesgm** [comment]
@jflatow Do you want to bump version and merge this?

**Comment by jflatow** [comment]
I suppose, was gonna try web3 2.x again, but lower priority than everything else right now and no need to conflate

**Pull request merged**
